# Generated by Django 4.1.1 on 2022-09-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dtime',
            field=models.DateField(verbose_name='Delivery datetime'),
        ),
    ]
