# Generated by Django 4.1.1 on 2022-09-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_service', '0002_alter_order_dtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dtime',
        ),
        migrations.AddField(
            model_name='order',
            name='ddate',
            field=models.DateField(default=None, verbose_name='Delivery date'),
        ),
    ]
