# Generated by Django 4.1.1 on 2022-09-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_service', '0003_remove_order_dtime_order_ddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='overdue_message',
            field=models.BooleanField(default=False, verbose_name='Sending message'),
        ),
    ]
